### ISSUE TITLE
segmentation fault with pgi 16.1

### ISSUE THREAD

**Issue by psteinb** [FFTW/fftw3#55]
Hi - 
I need to use fftw 3.3.4 with the pgi compiler 16.1. fftw does build with the following flags"

```
$ CC=pgcc CFLAGS="-O2 -fPIC" F77=pgfortran FFLAGS="-O2"  ./configure  --enable-avx --enable-openmp --enable-shared  --prefix=/home/steinba/software/fftw/3.3.4/pgi161-nompi
```

fftw builds, the checks fail and I see that the bench util runs into a segmentation fault when called like 

```
$ ./bench -s 64
Segmentation fault (core dumped)
```

The code can be compiled alright with pgi 15.9 and the bench utility runs just fine.
Any idea?

Thanks,
P

```
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.4 (Santiago)
Release:        6.4
Codename:       Santiago
$ uname -a
Linux tauruslogin4 2.6.32-504.3.3.el6.x86_64 #1 SMP Fri Dec 12 16:05:43 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by matteo-frigo** [comment]
No idea.

What instruction causes the segfault?

  gdb bench
  r -s 64
  x/i $pc

**Comment by psteinb** [comment]
this is a pgi 16.1 build binary, gdb is unable to run this binary. I'll try to use pgdbg.

**Comment by psteinb** [comment]
ok, I got a traceback, still working on pgdbg:

```
$ ./bench -s 64
Error: segmentation violation
   rax 00007fffc10765e0, rbx 0000000000000000, rcx 000000000000003c
   rdx 00007fffc10764a0, rsp 00007fffc1075df0, rbp 00007fffc1076350
   rsi 0000000000000002, rdi 00007fffc10765e0, r8  0000000000751940
   r9  00000000007518a0, r10 00007fffc1076070, r11 00007fdc52998c50
   r12 00000000004025d0, r13 00007fffc1077400, r14 0000000000000000
   r15 0000000000000000
  /lib64/libpthread.so.0() [0x3b33a0f710]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x21f82d) [0x7fdc52b6982d]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x5b11f) [0x7fdc529a511f]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x5b35d) [0x7fdc529a535d]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_dft_solve+0x4f) [0x7fdc529a8f8f]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x550cc) [0x7fdc5299f0cc]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_measure_execution_time+0x83) [0x7fdc5299f173]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x50fa6) [0x7fdc5299afa6]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x51263) [0x7fdc5299b263]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x513dd) [0x7fdc5299b3dd]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x51717) [0x7fdc5299b717]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_mkplan_d+0x22) [0x7fdc5299c0f2]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x58800) [0x7fdc529a2800]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x51078) [0x7fdc5299b078]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x511f5) [0x7fdc5299b1f5]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x513dd) [0x7fdc5299b3dd]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x51717) [0x7fdc5299b717]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x1bcb11) [0x7fdc52b06b11]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(+0x1bcb6c) [0x7fdc52b06b6c]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_mkapiplan+0x16c) [0x7fdc52b06d9c]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_plan_many_dft+0x1a6) [0x7fdc52b0c206]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_plan_dft+0x78) [0x7fdc52b0b448]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/.libs/libfftw3.so.3(fftw_plan_dft_1d+0x38) [0x7fdc52b0b058]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x4034fc]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x4037d5]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x403d26]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x404f45]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x406cf8]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x40532e]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x40578d]
  /lib64/libc.so.6(__libc_start_main+0xfd) [0x3b3321ed5d]
  /home/steinba/software/fftw/fftw-3.3.4-pgi-test/tests/.libs/lt-bench() [0x4025f9]
```

**Comment by psteinb** [comment]
wow, your bench script is lovely. anyway, I got some clue from pgdbg:

```
Signalled SIGSEGV at 0x7FF2B0F3ADA7, function VBYI, file simd-avx.h, line 236
  0x7FF2B0F3ADA7:  C5 FD 29 45 E0       vmovapd %ymm0,-32(%rbp)
```
Does that help?

**Comment by matteo-frigo** [comment]
This is very hard for me to debug remotely.  %rbp is usually the "frame pointer" (depending on compilation flags), so it would seem that the compiler is somehow writing to an unallocated stack location.  But it's hard to say much more than this (and what I said may well be wrong if the compiler is using rbp for some other purpose).

**Comment by psteinb** [comment]
Let me see if I can get PGI to have a look at it. I didn't find a bug 
tracker yet, just a user forum - but this looks like something for the 
former. I'll keep you posted.

**Comment by psteinb** [comment]
http://www.pgroup.com/userforum/viewtopic.php?p=20010#20010

**Comment by tdd11235813** [comment]
working on the same system as psteinb, I want to add some infos.
I do not get the problem when AVX is not used (no --enable-avx).
Flags used where problem occurs:
--enable-static=yes --enable-silent-rules --with-pic CFLAGS=-g --enable-openmp  --enable-avx
Segfaults do not occur everywhere, but always for the same "-s NUMBER". 
I have attached the runs and one stacktrace for -s 20.
Attachment: [pgi16_1_fftw334.txt](https://github.com/FFTW/fftw3/files/162921/pgi16_1_fftw334.txt)

**Comment by psteinb** [comment]
pgi reported they are looking into this,
https://www.pgroup.com/userforum/viewtopic.php?t=5127
I'll keep this issue open until further notive from PGI

**Comment by psteinb** [comment]
based on the pgi forum thread quoted above, this issue is fixed with pgi 16.9 and 16.10

**Comment by DarthLaran** [comment]
Unfortunately, the guy from the forum forgot to put --enable-avx during ./configure
and avoid following issue: https://github.com/FFTW/fftw3/issues/78#issuecomment-271079054

The version 3.3.4 builds OK with --enable-avx, but the segfault problem from this issue still exists at PGI 16.9

**Comment by psteinb** [comment]
@DarthLaran I informed the PGI folks
